[build]
builder = "NIXPACKS"
buildCommand = "NODE_ENV=development npm install && npm run build"

[deploy]
startCommand = "node server/index.js"
healthcheckPath = "/api/fechas-rango"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[volumes]]
mountPath = "/app/data"
